### ISSUE TITLE
Get predictions per token

### ISSUE THREAD

**Issue by emanjavacas** [hipster-philology/nlp-pie-taggers#6]
Hey! I like the idea of having this library to append pre- and post-processing steps to full tagging pipelines. As you know, I have been trying to run lasla from within another python script and I am running into issues. I understand the way you have structured the code with somebody in mind who wants to fully tag an input file. My only concern (which applies to many other taggers) is that it's very difficult to get the basics from it: to get token-level predictions for an input sentence.

The API I'd love to see is:

```
>>> tagger = load_tagger("...")
>>> tagger.tag([["First", "sentence"], ["Second", "sentence"])
[
   [{"lemma": "first", "pos": ...}, {"lemma": "sentence", ...}, ...],
   [{"lemma": "second", ...}, ...]
]
```

Having that basic block you can then build the more complex functionality on top. 

Right now, I am having this issue where I am getting different number of predictions than inputs, because of splits ("ibique" -> "ibi" "que"). Not sure if there is an easy way to fix this.

**Comment by PonteIneptique** [comment]
Damn, I think this is gonna be hard to do, but not undoable, mostly because you are working with pre-tokenized input... 

I think... you should be able to bypass to some extent the sentence_tokenizer and the word tokenizer. And then zip the GlueFormatter header to list of results.

On the other hand, the point for which you want to fix it is also "problematic" here. The issue I see with this is that `-que` and `-ne` are split in the training data, hence it being split here and hence it being important actually. So in the end, you would get bad results because input is not tokenized as it is in the training data... You see my point ?

**Comment by emanjavacas** [comment]
I imagine people are going to have different needs. Sometimes input is tokenized at the sentence level, sometimes sentence and word level and sometimes not tokenized at all. It'd be cool to have some control over that.

Anyway, all this only applies if you are planning to add some kind of python api. Right now I have to skip the header, because I only need the predictions. That's why I was thinking if you want to add the API, you could later build the output formatting (adding header etc...) to the output of the python API. That'd give people more control over what they want to do (get a tagged file or get predictions programmatically, etc...).

About the fix, I think the priority should be given to the format in the user input data, if you do split an input token, it could just be joined later in a post-processing step (the output could be a tuple for instance, and left to the user to combine the predicted tags or consider it different tokens).

**Comment by PonteIneptique** [comment]
I actually like your idea of potentially tupling stuff if the input should be tokenized another way. I have been working on alignment of output since yesterday and I can say it won't be easy...

As for the header and stuff, I agree we should have another class before Formatter that would be Post-Processing or so and generates dictionaries. This is basically technical debt I have not dealt with...

**Comment by emanjavacas** [comment]
No worries. I am not in a rush, but it is true that it'd be cool to have this. Also you could imagine people wanting to write their own pre(/post)processors for ad-hoc models. If you can come up with a nice API that could be really useful! 

Happy to help with all this.

**Comment by PonteIneptique** [comment]
Yup, agrees.
It's also a question of how far I can go from pie to get things working. First thing would be to look if that, somehow, was the reason for me to go for TSV output right at the begining.
If not, I am thinking this might be an easy fix to move from formatter to PostProcessing.

**Comment by PonteIneptique** [comment]
I'll take a shot at that right now, as I am lemmatizing my corpus...

**Comment by PonteIneptique** [comment]
(I mean take a shot at having postprocessing and formatting differentiated)

**Comment by PonteIneptique** [comment]
I had a small shot at it :) 

Still not there (buggy as hell), but there will soon be a better way to do postprocessing. You can definitely have a look, I'll be happy to get your feedback.

I focused at least for now at getting tokens and annotations together.

**Comment by PonteIneptique** [comment]
Link : https://github.com/hipster-philology/nlp-pie-taggers/commit/5f64babd02271f8b2264bec5208c142c12c196ce

**Comment by PonteIneptique** [comment]
I think this can be closed.
